<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.jenkins-ci.plugins</groupId>
    <artifactId>plugin</artifactId>
    <version>6.2221.va_045130417c9</version>
    <relativePath />
  </parent>

  <groupId>com.strayfarer.jenkins</groupId>
  <artifactId>pipeline-steps</artifactId>
  <version>${revision}</version>
  <packaging>hpi</packaging>

  <name>Strayfarer Pipeline Steps</name>
  <description>Generic Jenkins Pipeline steps for durable command execution, Docker sidecars, and execution across matching nodes.</description>
  <url>https://github.com/Strayfarer/com.strayfarer.jenkins.pipeline-steps</url>

  <licenses>
    <license>
      <name>MIT License</name>
      <url>https://opensource.org/license/mit</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <id>Faulo</id>
      <name>Daniel Schulz</name>
      <url>https://github.com/Faulo</url>
    </developer>
  </developers>

  <scm>
    <connection>scm:git:https://github.com/Strayfarer/com.strayfarer.jenkins.pipeline-steps.git</connection>
    <developerConnection>scm:git:git@github.com:Strayfarer/com.strayfarer.jenkins.pipeline-steps.git</developerConnection>
    <tag>${scmTag}</tag>
    <url>https://github.com/Strayfarer/com.strayfarer.jenkins.pipeline-steps</url>
  </scm>

  <properties>
    <revision>SNAPSHOT</revision>
    <scmTag>HEAD</scmTag>
    <jenkins.version>2.555.3</jenkins.version>
    <palantir.java.format.version>2.97.0</palantir.java.format.version>
    <spotless.check.skip>false</spotless.check.skip>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.jenkins.tools.bom</groupId>
        <artifactId>bom-2.555.x</artifactId>
        <version>6904.v75208ee5a_206</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.jenkins-ci.plugins.workflow</groupId>
      <artifactId>workflow-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jenkins-ci.plugins.workflow</groupId>
      <artifactId>workflow-cps</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jenkins-ci.plugins.workflow</groupId>
      <artifactId>workflow-durable-task-step</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jenkins-ci.plugins.workflow</groupId>
      <artifactId>workflow-step-api</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.code.findbugs</groupId>
      <artifactId>jsr305</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.jenkins-ci.main</groupId>
      <artifactId>jenkins-test-harness</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jenkins-ci.plugins.workflow</groupId>
      <artifactId>workflow-basic-steps</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jenkins-ci.plugins.workflow</groupId>
      <artifactId>workflow-job</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <repositories>
    <repository>
      <id>repo.jenkins-ci.org</id>
      <url>https://repo.jenkins-ci.org/public/</url>
    </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>repo.jenkins-ci.org</id>
      <url>https://repo.jenkins-ci.org/public/</url>
    </pluginRepository>
  </pluginRepositories>

  <build>
    <plugins>
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <configuration>
          <java combine.self="override">
            <endWithNewline />
            <forbidWildcardImports />
            <importOrder />
            <indent>
              <spaces>true</spaces>
            </indent>
            <palantirJavaFormat>
              <version>${palantir.java.format.version}</version>
            </palantirJavaFormat>
            <removeUnusedImports />
            <trimTrailingWhitespace />
          </java>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
